
all: game.cpp main.cpp player.cpp
	g++ player.cpp gameobject.cpp server.cpp client.cpp transferobject.cpp taskmanager.cpp tile.cpp maze.cpp menu.cpp music.cpp game.cpp main.cpp -lSDL2 -lSDL2_ttf -lSDL2_image -lSDL2_mixer -o game

clean:
	rm *.o game

